/* 「手机端顶栏瘦身 + 工具折叠」取证 · 第一步：注入实测脚本，供 headless Edge 出数。
 *
 * 运行： node verify/mobile-ui-gen.js
 *       然后（PowerShell，注意 headless 的 --window-size **管不了布局视口**，
 *       所以脚本自己把内容宽钉成 375px —— 与 narrow-evidence 同一套口径）：
 *         msedge --headless=new --disable-gpu --hide-scrollbars --allow-file-access-from-files `
 *                --user-data-dir=<tmp> --window-size=420,1000 --virtual-time-budget=20000 `
 *                --screenshot=docs/ui-mobile-tools.png --dump-dom `
 *                file:///D:/apps/tools/quiz-demo/verify/mobile-ui.html > verify\mobile-ui-dump.html
 *       最后： node verify/mobile-ui-parse.js
 *
 * 验的是用户这两句话：
 *   · "手机端 ui 得让上面那部分按钮可以折叠"  → 窄屏默认折起、点「工具」展开、控件一个不少且都 ≥44px；
 *   · "双端 ui 都删除顶部的答题全能版和简介小字" → 顶栏里没有 h1、没有那行简介（宽窄都不该有）。
 */
const fs = require('fs');
const path = require('path');
const HERE = path.join(__dirname, '..');

const DRIVER = [
  '(function () {',
  '  var lines = [], okAll = true;',
  '  function step(name, got, want) {',
  '    var pass = JSON.stringify(got) === JSON.stringify(want);',
  '    if (!pass) okAll = false;',
  '    lines.push((pass ? "PASS  " : "FAIL  ") + name + "  | 实测=" + JSON.stringify(got) + " 期望=" + JSON.stringify(want));',
  '  }',
  '  function note(t) { lines.push("----  " + t); }',
  '  function sleep(ms) { return new Promise(function (r) { setTimeout(r, ms); }); }',
  '  function vis(el) {',
  '    if (!el) return false;',
  '    var r = el.getBoundingClientRect();',
  '    if (r.width <= 0 || r.height <= 0) return false;',
  '    var s = getComputedStyle(el);',
  '    return s.visibility !== "hidden" && s.display !== "none";',
  '  }',
  '  function flush() {',
  '    var pre = document.getElementById("drvReport");',
  '    if (!pre) { pre = document.createElement("pre"); pre.id = "drvReport"; document.body.appendChild(pre); }',
  '    pre.textContent = lines.join("\\n");',
  '    pre.style.display = "none";            /* 明细留在 dump 里（parse 读得到），别印在截图上 */',
  '    var box = document.getElementById("drvHud");',
  '    if (!box) { box = document.createElement("div"); box.id = "drvHud"; document.body.appendChild(box); }',
  '    box.style.cssText = "position:fixed;left:0;bottom:0;right:0;z-index:99999;background:rgba(0,0,0,.9);color:#9f9;"',
  '      + "font:11px/1.5 Consolas,monospace;padding:5px 7px;max-height:22vh;overflow:auto;white-space:pre-wrap;word-break:break-all";',
  '    box.textContent = "[手机端顶栏 · 实测]\\n" + lines.join("\\n");',
  '    document.title = "手机端顶栏 " + (okAll ? "ALL PASS" : "有 FAIL") + " (" + lines.length + " 条)";',
  '    try { window.scrollTo(0, 0); } catch (x) { /* ignore */ }',
  '    var list = document.querySelector(".qp-list"); if (list) list.scrollTop = 0;',
  '  }',
  '  window.addEventListener("error", function (e) {',
  '    lines.push("FAIL  页面抛错：" + (e && (e.message || e.error) || e));',
  '    try { flush(); } catch (x) { /* ignore */ }',
  '  });',
  '  async function run() {',
  '    try {',
  '      /* ⓪ 先把内容宽钉成 375px（与 narrow-evidence 同一口径：headless 的 window-size 管不了布局视口） */',
  '      var st = document.createElement("style");',
  '      st.textContent = "html{width:375px !important}body{width:375px !important;max-width:375px !important}";',
  '      document.head.appendChild(st);',
  '      await sleep(200);',
  '      var de = document.documentElement;',
  '      note("内容宽 = " + Math.round(document.body.getBoundingClientRect().width) + "px（视口 " + de.clientWidth + "）");',
  '',
  '      /* ① 顶栏：标题与简介小字都删掉了（双端） */',
  '      var top = document.querySelector(".top");',
  '      step("顶栏里没有大标题（h1）", top ? top.querySelectorAll("h1").length : -1, 0);',
  '      step("顶栏里没有那行简介小字（#appTip 不存在）", !!document.getElementById("appTip"), false);',
  '      var topText = String(top ? top.textContent : "");',
  '      step("  顶栏文字里也没有「答题全能版」「四件事」这些字样",',
  '           [/答题全能版/.test(topText), /四件事/.test(topText)], [false, false]);',
  '      note("顶栏实际文字 = " + JSON.stringify(topText.replace(/\\s+/g, " ").trim().slice(0, 40)));',
  '      var tabs = document.querySelectorAll(".top .tab");',
  '      step("  那一排还在（省下的只是标题与简介，不是导航）—— 3 个页签 + 「导出分享」+ 「须知」", tabs.length, 5);',
  '',
  '      /* ② 导入 / 校对页：工具栏窄屏默认折起 */',
  '      document.getElementById("tab-review").click();',
  '      await sleep(150);',
  '      var row = document.getElementById("revTools");',
  '      var body = document.getElementById("revToolsBody");',
  '      var tog = document.getElementById("revToolsToggle");',
  '      step("工具栏有折叠容器与折叠按钮", [!!row, !!body, !!tog], [true, true, true]);',
  '      step("  折叠按钮在窄屏**看得见**", vis(tog), true);',
  '      step("  而且触控高度 ≥44px", Math.round(tog.getBoundingClientRect().height) >= 44, true);',
  '      var tb = tog.getBoundingClientRect();',
  '      note("折叠按钮 " + Math.round(tb.width) + "x" + Math.round(tb.height) + "px，文案 = " + JSON.stringify(tog.textContent));',
  '      step("  默认**折起来**（工具那一块不可见）", vis(body), false);',
  '      step("  按钮文案说清点它会展开（带 ▾）", /工具/.test(String(tog.textContent)), true);',
  '',
  '      /* ③ 点一下展开：8 个控件一个不少、都在 375px 列内、都 ≥44px */',
  '      tog.click();',
  '      await sleep(150);',
  '      step("点一下 → 工具那块露出来", vis(body), true);',
  '      step("  按钮文案变成「收起工具 ▴」", /收起工具/.test(String(tog.textContent)), true);',
  '      var ids = ["revDemo", "revClear", "revDrop", "revAikey", "revAibatch"];',
  '      var missing = ids.filter(function (id) { var n = document.getElementById(id); return !n || !vis(n); });',
  '      step("  展开后 5 个可见入口全部在（拖入区 / AI 密钥 / 生成解析 / 载入样卷 / 清空）", missing, []);',
  '      /* 文件输入框本身是 display:none（藏在 label 后面），所以单独验：它**存在**、label 可见且 ≥44px */',
  '      var fi = document.getElementById("revFile");',
  '      var fl = document.querySelector("label.file[for=\\"revFile\\"]");',
  '      step("  文件输入框在（藏起来的那种）且它的 label 可见、≥44px",',
  '           [!!fi, vis(fl), fl ? Math.round(fl.getBoundingClientRect().height) >= 44 : false], [true, true, true]);',
  '      var small = [];',
  '      ids.forEach(function (id) {',
  '        var n = document.getElementById(id);',
  '        if (n && vis(n) && n.tagName !== "INPUT") {',
  '          var r = n.getBoundingClientRect();',
  '          if (r.height < 44) small.push(id + " " + Math.round(r.width) + "x" + Math.round(r.height));',
  '        }',
  '      });',
  '      step("  每个入口的触控高度都 ≥44px", small, []);',
  '      var cw = Math.round(document.body.getBoundingClientRect().width);',
  '      var spill = [];',
  '      ids.forEach(function (id) {',
  '        var n = document.getElementById(id);',
  '        if (n && vis(n) && Math.round(n.getBoundingClientRect().right) > cw + 1) spill.push(id);',
  '      });',
  '      step("  展开后也没有横向溢出（都落在 375px 列内）", spill, []);',
  '      step("  页面没有横向滚动", de.scrollWidth <= de.clientWidth, true);',
  '',
  '      /* ③-b 本轮追加：**页签那一排也能折**（用户要求"让这一排再手机端 ui 可折叠"） */',
  '      var tabsTog = document.getElementById("tabsToggle");',
  '      var tabsBar = document.getElementById("tabsBar");',
  '      var tabsRow = document.getElementById("tabsRow");',
  '      var tabShare = document.getElementById("tab-share");',
  '      step("手机端：页签那一排有折叠按钮，而且看得见", [!!tabsTog, vis(tabsTog)], [true, true]);',
  '      step("  触控高度 ≥44px", tabsTog ? Math.round(tabsTog.getBoundingClientRect().height) >= 44 : false, true);',
  '      /* 用户要求："在首页时自动切换为展开模式" —— 启动落在题库首页，所以一进来整排就是铺开的 */',
  '      step("**首页自动展开**（用户要求）：一进来整排就是铺开的", vis(tabsBar), true);',
  '      step("  此刻按钮写「收起 ▴」", String(tabsTog.textContent).trim(), "收起 ▴");',
  '      tabsTog.click();                          // 手动收起：好验收起态那几条',
  '      await sleep(150);',
  '      step("点一下 → **收起来**（整排藏起来，把那一行还给正文）", vis(tabsBar), false);',
  '      /* 用户要求："收起的时候让按钮显示展开"（早先写的是当前页名） */',
  '      step("  **收起时按钮显示「展开 ▾」**", String(tabsTog.textContent).trim(), "展开 ▾");',
  '      /* 用户要求："收起之后做成悬浮形式不要占一排位置" —— 收起态是 position:fixed，且不占流里的高度 */',
  '      step("  收起态是**悬浮**的（position:fixed，脱离文档流）",',
  '           (function () { var cs = getComputedStyle(tabsRow); return cs.position; })(), "fixed");',
  '      step("  它不再占页面上那一排的位置（收起时整块高度 ≈ 只有那颗按钮那么高，且不在流里推正文）",',
  '           [Math.round(tabsRow.getBoundingClientRect().top) <= 12,',
  '            Math.round(tabsRow.getBoundingClientRect().right) >= window.innerWidth - 24], [true, true]);',
  '      tabsTog.click();',
  '      await sleep(150);',
  '      step("点一下 → 整排铺出来（5 个按钮：答题 / 导入 校对 / 错题本 / 导出分享 / 须知）",',
  '           [vis(tabsBar), document.querySelectorAll(".tabs .tab").length, !!tabShare], [true, 5, true]);',
  '      step("  展开时回到正常流（position 不再是 fixed，那一排摆在该在的位置）",',
  '           (function () { return getComputedStyle(tabsRow).position; })(), "static");',
  '      var tabBoxes = Array.prototype.slice.call(document.querySelectorAll(".tabs .tab"));',
  '      step("  五个都可见、都 ≥44px（手机上 375 宽会自然换成两行，这条只量可点性）",',
  '           [tabBoxes.length, tabBoxes.every(function (b) { return vis(b) && Math.round(b.getBoundingClientRect().height) >= 44; })], [5, true]);',
  '      step("  而且都没有横向溢出（右缘在 375px 列内）",',
  '           Math.round(Math.max.apply(null, Array.prototype.map.call(document.querySelectorAll(".tabs .tab"), function (b) {',
  '             return b.getBoundingClientRect().right; }))) <= Math.round(document.body.getBoundingClientRect().width) + 1, true);',
  '      /* 用户要求："顶部栏点击跳转之后不要自动收起" —— 点页签 / 点导出分享之后整排必须**还在** */',
  '      document.getElementById("tab-answer").click();',
  '      await sleep(200);',
  '      step("点页签跳转（答题）→ **整排不自动收起**（用户要求）", vis(tabsBar), true);',
  '      step("  按钮文案跟着当前页走（此刻是「收起 ▴」：它还开着）", String(tabsTog.textContent).trim(), "收起 ▴");',
  '      step("  真的跳过去了（答题面板可见、导入面板收起）",',
  '           [document.getElementById("pane-answer").hidden, document.getElementById("pane-review").hidden], [false, true]);',
  '      tabsTog.click();',                       // 展开态 → 手动收起
  '      await sleep(150);',
  '      step("  手动收起后按钮写「展开 ▾」（不再写当前页名）", String(tabsTog.textContent).trim(), "展开 ▾");',
  '      tabsTog.click();',                       // 再展开：继续验导出分享那一条
  '      await sleep(150);',
  '      tabShare.click();',
  '      await sleep(200);',
  '      step("点「导出分享」→ 整排**也不自动收起**（只更新文案）", vis(tabsBar), true);',
  '      step("  选卷页出来了", !!document.querySelector("#sharePage .share-card"), true);',
  '      step("  选卷页按钮都 ≥44px", (function () {',
  '             var bad = [];',
  '             Array.prototype.slice.call(document.querySelectorAll("#sharePage .share-acts .big")).forEach(function (b) {',
  '               if (vis(b) && Math.round(b.getBoundingClientRect().height) < 44) bad.push(String(b.textContent).slice(0, 6));',
  '             });',
  '             return bad;',
  '           })(), []);',
  '      var cancelShare = document.getElementById("shareCancel");',
  '      if (cancelShare) { cancelShare.click(); await sleep(150); }',
  '      step("  关掉选卷页之后整排还开着（没人替用户收起）", vis(tabsBar), true);',
  '      /* ---------- 用户要求：顶部那一栏加一项「须知」（声明与警告都收进去） ---------- */',
  '      var helpBtn = document.getElementById("tab-help");',
  '      step("顶栏那一排有「须知」按钮", !!helpBtn, true);',
  '      step("  它也是 ≥44px 的真按钮", helpBtn ? Math.round(helpBtn.getBoundingClientRect().height) >= 44 : false, true);',
  '      helpBtn.click();',
  '      await sleep(200);',
  '      var hp = document.getElementById("helpPage");',
  '      step("点它 → 整页须知打开（不是跳走）", !!(hp && !/hidden/.test(String(hp.className))), true);',
  '      step("  打开时顺手把页签那排收起来（浮层上不再压一排按钮）", vis(tabsBar), false);',
  '      var htxt = String(hp.textContent);',
  '      step("  有简易使用说明（三步 + 常用按钮）",',
  '           [/怎么用（三步）/.test(htxt), /常用按钮/.test(htxt)], [true, true]);',
  '      /* 文档截图用：#shot=help 停在须知页顶部；#shot=credit 滚到底（看得见链接与署名那一行）——',
  '       *   credit 那一张要**把 HUD 藏掉**：它就压在屏幕底部，会把最后那几行盖住（自己骗自己）。 */',
  '      var SHOTMODE = String(location.hash).replace(/^#(?:shot=)?/, "");',
  '      if (SHOTMODE === "help" || SHOTMODE === "credit") {',
  '        try { hp.querySelector(".help-card").scrollIntoView({ block: (SHOTMODE === "credit" ? "end" : "start") }); } catch (e0) { /* ignore */ }',
  '        flush();',
  '        if (SHOTMODE === "credit") {',
  '          var hud = document.getElementById("drvHud"); if (hud) hud.style.display = "none";',
  '          var rep = document.getElementById("drvReport"); if (rep) rep.style.display = "none";',
  '          try { hp.scrollTop = hp.scrollHeight; } catch (e1) { /* ignore */ }',
  '          try { window.scrollTo(0, document.documentElement.scrollHeight); } catch (e2) { /* ignore */ }',
  '        }',
  '        return;',
  '      }',
  '      step("  有「声明与警告」小节，且九条声明都在",',
  '           [["数据只存你本机", "只有 AI 功能需要联网", "AI 密钥只存本机", "分享文件只带试卷", "下载可能被拦",',
  '             "删除不可恢复", "存储不可用或写满", "判分口径", "内容自负"]',
  '              .every(function (t2) { return htxt.indexOf(t2) >= 0 })], [true]);',
  '      step("  小字里有 GitHub 主页与项目仓库地址",',
  '           [hp.querySelectorAll(\'a[href*="github.com/kokuraasahidesu"]\').length >= 2], [true]);',
  '      step("  也有邮箱那一行（写的是作者给的地址）", htxt.indexOf("liyi07@outlook.com") >= 0, true);',
  '      step("  最下面写着制作署名",',
  '           htxt.indexOf("由北京理工大学 2625 李佳祎使用 DeepSeek V4.1 Flash 和亲爱的一百块钱制作") >= 0, true);',
  '      step("  须知里的链接都待在卡片里（没有被裁掉/溢出）",',
  '           (function () {',
  '             var card = hp.querySelector(".help-card");',
  '             if (!card) return -1;',
  '             var cr = card.getBoundingClientRect();',
  '             return Array.prototype.filter.call(hp.querySelectorAll("a"), function (a) {',
  '               var r = a.getBoundingClientRect();',
  '               return r.right > cr.right + 1 || r.left < cr.left - 1;',
  '             }).length;',
  '           })(), 0);',
  '      var hclose = document.getElementById("helpClose");',
  '      step("  有「关闭」按钮且 ≥44px", hclose ? Math.round(hclose.getBoundingClientRect().height) >= 44 : false, true);',
  '      if (hclose) { hclose.click(); await sleep(150); }',
  '      step("  点关闭 → 收起来", vis(hp), false);',
  '      /* 用户要求：制作人信息**只写在须知里**（页脚不再写） */',
  '      step("  页脚**不再**写制作人信息（只剩一句指路）",',
  '           (function () { var f = document.getElementById("footMore");',
  '             var foot = document.querySelector(".foot");',
  '             return !!(f && f.textContent.indexOf("须知") >= 0 && String(foot.textContent).indexOf("李佳祎") < 0); })(), true);',
  '      /* ⚠ 打开须知时那一排已经被收起来了（上面那条断言过），这里**不要再点一次** ——',
  '       *   再点一下是"展开"，会让下面那条"藏起来"的断言假红（第一版就这么写错了）。 */',
  '      step("  关掉须知之后整排仍是收起的（还我悬浮那颗按钮）", vis(tabsBar), false);',
  '      await sleep(120);',
  '',
  '      /* ④ 再点一下收回去（能开也能收，不是一次性的） */',
  '      tog.click();',
  '      await sleep(150);',
  '      step("再点一下 → 又收起来", vis(body), false);',
  '      step("  文案回到「工具 ▾」", /工具/.test(String(tog.textContent)) && !/收起/.test(String(tog.textContent)), true);',
  '',
  '      /* ⑤ 折叠的意义：正文（入库 JSON 框）不再被工具块推到屏幕外 */',
  '      var out = document.getElementById("revOut");',
  '      var outTop = out ? Math.round(out.getBoundingClientRect().top) : -1;',
  '      note("折叠状态下 .out（入库后显示 JSON 的地方）top = " + outTop + "px / 视口高 " + window.innerHeight);',
  '      step("  正文在首屏里（不再被工具那四行推到屏幕外）", outTop >= 0 && outTop < window.innerHeight, true);',
  '      step("  折叠后工具块高度 = 0（真的收干净了）", Math.round(body.getBoundingClientRect().height), 0);',
  '',
  '      /* ⚠ "宽屏不折"这一条**不在这里验**：本页把内容宽钉成 375px，而折叠规则用的是媒体查询',
  '       *   （看**视口**宽，不看内容宽）—— 钉宽度改不了视口，量不出宽屏那一侧。',
  '       *   那一条由 verify/import-bank-gen.js 在 1280px 窗口里验（那边的拖入区必须一直可见）。 */',
  '    } catch (e) {',
  '      okAll = false; lines.push("FAIL  驱动抛错：" + (e && e.stack || e));',
  '    }',
  '    flush();',
  '  }',
  '  if (document.readyState === "complete") setTimeout(run, 900);',
  '  else window.addEventListener("load", function () { setTimeout(run, 900); });',
  '})();'
].join('\n');

try { new Function(DRIVER); } catch (e) { throw new Error('注入脚本有语法错误：' + e.message); }

const src = fs.readFileSync(path.join(HERE, 'review_quiz.html'), 'utf8');
const at = src.lastIndexOf('</body>');
if (at < 0) throw new Error('没找到 </body>');
fs.writeFileSync(path.join(HERE, 'verify', 'mobile-ui.html'), src.slice(0, at) + '<script>\n' + DRIVER + '\n<\/script>\n' + src.slice(at), 'utf8');
console.log('generated verify/mobile-ui.html（注入点 ' + at + '）');
